[package]
name = "rs-arrow-ipc-stream-cat"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/takanoriyanagitani/rs-arrow-ipc-stream-cat"
license = "Apache-2.0"
description = "CLI to show the ipc stream.",
keywords = ["arrow", "ipc", "stream"],
homepage = "https://github.com/takanoriyanagitani/rs-arrow-ipc-stream-cat",
documentation = "https://docs.rs/rs-arrow-ipc-stream-cat/latest",

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[dependencies]
arrow = { version = "56", features = ["prettyprint"] }
arrow-array = "56"
arrow-cast = "56"
arrow-ipc = "56"
arrow-schema = "56"
clap = { version = "4", features = ["derive"] }
